from conectando_banco_de_dados import conectando_ao_banco

def consulta_dados_banco(date_inicial: str, date_final: str):
    
    cursor = conectando_ao_banco()
    print('\n')
    print('Carregando banco de dados, aguarde: \n')
    
    
    var_query = """
    SELECT        
	FORMAT(DATA,'dd-MM-yyyy') AS DATA,
    FORMAT(DATA,'HH:mm:ss') as HORA,
	ARQUIVO AS ARQUIVO,
	DURACAO AS DURACAO,
	CPF_OPERADOR AS CPF,
	NOME AS TABULACAO,
	ORIGEM AS ORIGEM,
	'CPC' AS TIPO ,
	RIGHT(TELEFONE,11) AS TELEFONE,
	CONTRATO AS CONTRATO,
	ASSESSORIA AS ASSESSORIA,
	NOME_OPERADOR AS NOME
	FROM OPENQUERY (TOTALIP,
	'SELECT B.DATA,
	NULL AS ARQUIVO,
	B.DURACAO,
	NULL AS CPF_OPERADOR,
	NULL AS NOME_OPERADOR,
	C.NOME,
	''RECEPTIVO'' AS ORIGEM,
	NULL TIPO_OCOR,
	B.ORIGEM AS TELEFONE,
	NULL AS CONTRATO,
	''ICR'' AS ASSESSORIA
	FROM HISTORICOS_ATIVOS_RECEPTIVOS A
	INNER JOIN LIGACOES_RECEPTIVO B ON A.ID_LIGACOES_RECEPTIVO = B.ID
	INNER JOIN STATUS_LIGACAO C ON A.ID_STATUS_LIGACAO = C.ID
	WHERE A.ID_STATUS_LIGACAO NOT IN (1,2,3)
	AND A.DATA BETWEEN ''2025-04-02 00:00:00.000'' AND ''2025-04-04 00:00:00.000''
	') A WHERE NOME LIKE '%DAYCOVAL%'
	UNION 
	SELECT        
	FORMAT(DATA,'dd-MM-yyyy'),
    FORMAT(DATA,'HH:mm:ss'),
	ARQUIVO  ,
	DURACAO  ,
	CPF_OPERADOR  ,
	NOME,
	ORIGEM,
	'CPC',
	RIGHT(TELEFONE,11),
	CONTRATO,
	ASSESSORIA ,
	NOME_OPERADOR
	FROM OPENQUERY (TOTALIP,
	'SELECT B.DATA,
	NULL AS ARQUIVO,
	B.DURACAO,
	NULL AS CPF_OPERADOR,
	NULL AS NOME_OPERADOR,
	C.NOME,
	''ATIVO'' AS ORIGEM,
	NULL TIPO_OCOR,
	B.DESTINO AS TELEFONE,
	NULL AS CONTRATO,
	''ICR'' AS ASSESSORIA
	FROM HISTORICOS_ATIVOS_RECEPTIVOS A
	INNER JOIN LIGACOES_ATIVO B ON A.ID_LIGACOES_ATIVO = B.ID
	INNER JOIN STATUS_LIGACAO C ON A.ID_STATUS_LIGACAO = C.ID
	WHERE A.ID_STATUS_LIGACAO NOT IN (1,2,3)
	AND A.DATA BETWEEN ''2025-04-02 00:00:00.000'' AND ''2025-04-03 00:00:00.000''
	') B WHERE NOME LIKE '%DAYCOVAL%'
    """



        
    
    cursor.execute(var_query)
    return cursor.fetchall()




